// renderers/lit/src/v0_9/catalogs/basic/components/Tabs.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {html, nothing, css} from 'lit';
import {customElement, state} from 'lit/decorators.js';
import {classMap} from 'lit/directives/class-map.js';
import {TabsApi} from '@a2ui/web_core/v0_9/basic_catalog';
import {BasicCatalogA2uiLitElement} from '../basic-catalog-a2ui-lit-element.js';
import {A2uiController} from '../../../a2ui-controller.js';

@customElement('a2ui-tabs')
export class A2uiLitTabs extends BasicCatalogA2uiLitElement<typeof TabsApi> {
  /**
   * The styles of the tabs can be customized by redefining the following
   * CSS variables:
   *
   * - `--a2ui-tabs-header-background`: Default transparent.
   * - `--a2ui-tabs-header-background-active`: Default `--a2ui-color-secondary`.
   * - `--a2ui-tabs-header-color`: Default `--a2ui-color-on-surface`.
   * - `--a2ui-tabs-header-color-active`: Default `--a2ui-color-on-secondary`.
   * - `--a2ui-tabs-border`: Default `--a2ui-border-width` solid `--a2ui-color-border`.
   * - `--a2ui-tabs-content-padding`: Default `0 var(--a2ui-spacing-m, 0.5rem)`.
   */
  static override styles = css`
    :host,
    a2ui-tabs {
      display: block;
    }
    .a2ui-tabs-headers {
      display: flex;
      gap: var(--a2ui-spacing-xs, 0.25rem);
      border-bottom: var(
        --a2ui-tabs-border,
        var(--a2ui-border-width, 1px) solid var(--a2ui-color-border, #ccc)
      );
      margin-bottom: var(--a2ui-spacing-m, 0.5rem);
    }
    .a2ui-tabs-header {
      padding: var(--a2ui-spacing-m, 0.5rem) var(--a2ui-spacing-l, 1rem);
      background: var(--a2ui-tabs-header-background, transparent);
      color: var(--a2ui-tabs-header-color, var(--a2ui-color-on-surface));
      border: none;
      border-radius: var(--a2ui-border-radius, 0.25rem) var(--a2ui-border-radius, 0.25rem) 0 0;
      cursor: pointer;
      font-family: inherit;
    }
    .a2ui-tabs-header.active {
      background: var(--a2ui-tabs-header-background-active, var(--a2ui-color-secondary, #eee));
      color: var(--a2ui-tabs-header-color-active, var(--a2ui-color-on-secondary, #333));
    }
    .a2ui-tabs-content {
      padding: var(--a2ui-tabs-content-padding, 0 var(--a2ui-spacing-m, 0.5rem));
    }
  `;

  protected createController() {
    return new A2uiController(this, TabsApi);
  }

  @state() accessor activeIndex = 0;

  override render() {
    const props = this.controller.props;
    if (!props || !props.tabs) return nothing;
    return html`
      <div class="a2ui-tabs-headers">
        ${props.tabs.map(
          (tab: any, i: number) => html`
            <button
              class=${classMap({
                'a2ui-tabs-header': true,
                'a2ui-tab-button': true,
                active: i === this.activeIndex,
              })}
              @click=${() => (this.activeIndex = i)}
            >
              ${tab.title}
            </button>
          `,
        )}
      </div>
      <div class="a2ui-tabs-content">
        ${props.tabs[this.activeIndex]
          ? html`${this.renderNode(props.tabs[this.activeIndex].child)}`
          : nothing}
      </div>
    `;
  }
}

export const A2uiTabs = {
  ...TabsApi,
  tagName: 'a2ui-tabs',
};

// renderers/react/src/v0_9/catalog/basic/components/Tabs.tsx
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {useState} from 'react';
import {createComponentImplementation} from '../../../../adapter';
import {TabsApi} from '@a2ui/web_core/v0_9/basic_catalog';
import {useBasicCatalogStyles} from '../utils';

// The type of a tab is deeply nested into the TabsApi schema, and
// it seems z.infer is not inferring it correctly (?). We use `any` for now.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type _Tab = any;

export const Tabs = createComponentImplementation(TabsApi, ({props, buildChild}) => {
  useBasicCatalogStyles();
  const [selectedIndex, setSelectedIndex] = useState(0);

  const tabs = props.tabs || [];
  const activeTab = tabs[selectedIndex];

  const tabsContainer: React.CSSProperties = {
    display: 'block',
  };

  const tabsHeaders: React.CSSProperties = {
    display: 'flex',
    gap: 'var(--a2ui-spacing-xs, 0.25rem)',
    borderBottom:
      'var(--a2ui-tabs-border, var(--a2ui-border-width, 1px) solid var(--a2ui-color-border, #ccc))',
    marginBottom: 'var(--a2ui-spacing-m, 0.5rem)',
  };

  const tabsHeaderBase: React.CSSProperties = {
    padding: 'var(--a2ui-spacing-m, 0.5rem) var(--a2ui-spacing-l, 1rem)',
    background: 'var(--a2ui-tabs-header-background, transparent)',
    color: 'var(--a2ui-tabs-header-color, var(--a2ui-color-on-surface))',
    border: 'none',
    borderRadius: 'var(--a2ui-border-radius, 0.25rem) var(--a2ui-border-radius, 0.25rem) 0 0',
    cursor: 'pointer',
    fontFamily: 'inherit',
  };

  const tabsHeaderActive: React.CSSProperties = {
    background: 'var(--a2ui-tabs-header-background-active, var(--a2ui-color-secondary, #eee))',
    color: 'var(--a2ui-tabs-header-color-active, var(--a2ui-color-on-secondary, #333))',
  };

  const content: React.CSSProperties = {
    padding: 'var(--a2ui-tabs-content-padding, 0 var(--a2ui-spacing-m, 0.5rem))',
  };

  return (
    <div style={tabsContainer}>
      <div style={tabsHeaders}>
        {tabs.map((tab: _Tab, i: number) => (
          <button
            key={i}
            className={`a2ui-tabs-header a2ui-tab-button ${selectedIndex === i ? 'active' : ''}`}
            onClick={() => setSelectedIndex(i)}
            style={{
              ...tabsHeaderBase,
              ...(selectedIndex === i ? tabsHeaderActive : {}),
            }}
          >
            {tab.title}
          </button>
        ))}
      </div>
      <div style={content}>{activeTab ? buildChild(activeTab.child) : null}</div>
    </div>
  );
});
