// renderers/lit/src/v0_9/directives/markdown.ts
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {html, noChange} from 'lit';
import {Directive, DirectiveParameters, Part, directive} from 'lit/directive.js';
import {unsafeHTML} from 'lit/directives/unsafe-html.js';
import {until} from 'lit/directives/until.js';
import type {MarkdownRenderer, MarkdownRendererOptions} from '@a2ui/web_core/v0_9';

class MarkdownDirective extends Directive {
  private lastValue: string | null = null;
  private lastTagClassMap: string | null = null;

  override update(
    _part: Part,
    [value, markdownRenderer, markdownOptions]: DirectiveParameters<this>,
  ) {
    const jsonTagClassMap = JSON.stringify(markdownOptions?.tagClassMap);
    if (this.lastValue === value && jsonTagClassMap === this.lastTagClassMap) {
      return noChange;
    }

    this.lastValue = value;
    this.lastTagClassMap = jsonTagClassMap;
    return this.render(value, markdownRenderer, markdownOptions);
  }

  private static defaultMarkdownWarningLogged = false;
  /**
   * Renders the markdown string to HTML using the injected markdown renderer,
   * if present. Otherwise, it returns the value wrapped in a span.
   */
  render(
    value: string,
    markdownRenderer?: MarkdownRenderer,
    markdownOptions?: MarkdownRendererOptions,
  ) {
    if (markdownRenderer) {
      const rendered = markdownRenderer(value, markdownOptions).then(value => {
        // `value` is a plain string, which we need to convert to a template
        // with the `unsafeHTML` directive.
        // It is the responsibility of the markdown renderer to sanitize the HTML.
        return unsafeHTML(value);
      });
      // The until directive lets us render a placeholder *until* the rendered
      // content resolves.
      return until(rendered, html`<span class="no-markdown-renderer">${value}</span>`);
    }

    if (!MarkdownDirective.defaultMarkdownWarningLogged) {
      console.warn(
        '[MarkdownDirective]',
        "can't render markdown because no markdown renderer is configured.\n",
        'Use `@a2ui/markdown-it`, or your own markdown renderer.',
      );
      MarkdownDirective.defaultMarkdownWarningLogged = true;
    }
    return html`<span class="no-markdown-renderer">${value}</span>`;
  }
}

export const markdown = directive(MarkdownDirective);

// renderers/angular/src/v0_9/core/markdown.ts
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Injectable} from '@angular/core';

export interface MarkdownRendererOptions {
  tagClassMap?: Record<string, string>;
}

export abstract class MarkdownRenderer {
  abstract render(markdown: string, options?: MarkdownRendererOptions): Promise<string>;
}

@Injectable({
  providedIn: 'root',
})
export class DefaultMarkdownRenderer extends MarkdownRenderer {
  private static warningLogged = false;

  override async render(markdown: string, _options?: MarkdownRendererOptions): Promise<string> {
    if (!DefaultMarkdownRenderer.warningLogged) {
      console.warn(
        '[DefaultMarkdownRenderer] No MarkdownRenderer configured. Plain text fallback used. ' +
          'Provide a renderer via `provideMarkdownRenderer(...)` with `@a2ui/markdown-it` if markdown formatting is required.',
      );
      DefaultMarkdownRenderer.warningLogged = true;
    }
    return markdown;
  }
}

export function provideMarkdownRenderer(
  renderFn?: (markdown: string, options?: MarkdownRendererOptions) => Promise<string>,
) {
  if (renderFn) {
    return {
      provide: MarkdownRenderer,
      useValue: {
        render: renderFn,
      },
    };
  }
  return {provide: MarkdownRenderer, useClass: DefaultMarkdownRenderer};
}
