// renderers/react/src/v0_9/A2uiSurface.tsx
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Surface renderer driven by the node layer.
 *
 * `A2uiSurface` owns one `NodeResolver` for the surface it is given,
 * subscribes to the resolved root node, and renders it through `NodeView`
 * under `NodeSurfaceContext`. Everything below the root, including dispatch
 * to each implementation and child reference resolution, lives in
 * `node-view.tsx`.
 */

import React, {useCallback, useMemo, useSyncExternalStore} from 'react';
import {NodeResolver, effect, getValue, peekValue, type SurfaceModel} from '@a2ui/web_core/v0_9';
import type {ReactCatalogComponent} from './react_component_implementation';
import {LoadingPlaceholder, NodeSurfaceContext, NodeView} from './node-view';

export const A2uiSurface: React.FC<{
  surface: SurfaceModel<ReactCatalogComponent>;
}> = ({surface}) => {
  // The resolver is created inside subscribe, which React calls only for
  // committed renders: a render that is discarded (concurrent mode,
  // Suspense) never constructs one, and every constructed resolver is
  // disposed by its own unsubscribe. StrictMode's double mount creates and
  // disposes two in turn.
  // The factory reads nothing; the dependency exists to reset the box when
  // the surface is swapped.
  const box = useMemo(
    () => ({resolver: undefined as NodeResolver<ReactCatalogComponent> | undefined}),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [surface],
  );
  const subscribe = useCallback(
    (onChange: () => void) => {
      const resolver = new NodeResolver(surface, surface.catalog);
      box.resolver = resolver;
      const stopEffect = effect(() => {
        getValue(resolver.rootNode);
        onChange();
      });
      return () => {
        stopEffect();
        resolver.dispose();
        if (box.resolver === resolver) {
          box.resolver = undefined;
        }
      };
    },
    [surface, box],
  );
  const getSnapshot = useCallback(
    () => (box.resolver ? peekValue(box.resolver.rootNode) : undefined),
    [box],
  );
  const root = useSyncExternalStore(subscribe, getSnapshot);

  if (!root) {
    return <LoadingPlaceholder componentId="root" />;
  }
  return (
    <NodeSurfaceContext.Provider value={surface}>
      <NodeView surface={surface} node={root} />
    </NodeSurfaceContext.Provider>
  );
};

// renderers/lit/src/v0_9/surface/a2ui-surface.ts
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {html, nothing, LitElement, PropertyValues} from 'lit';
import {customElement, property, state} from 'lit/decorators.js';
import {SurfaceModel, ComponentContext} from '@a2ui/web_core/v0_9';
import {renderA2uiNode} from './render-a2ui-node.js';
import {LitComponentApi} from '../types.js';

/**
 * A Lit component that renders an A2UI Surface.
 *
 * This component takes a `SurfaceModel` and dynamically renders the root component
 * and its children using the provided catalog. It handles loading states if the
 * root component is not yet available.
 *
 * @element a2ui-surface
 */
@customElement('a2ui-surface')
export class A2uiSurface extends LitElement {
  /**
   * The surface model containing the component tree and catalog.
   */
  @property({type: Object}) accessor surface: SurfaceModel<LitComponentApi> | undefined;

  /**
   * Internal state indicating whether the root component exists.
   * @internal
   */
  @state() accessor _hasRoot = false;
  /**
   * Subscription cleanup function.
   * @internal
   */
  private unsubscribe?: () => void;

  /**
   * Handles lifecycle updates, specifically when the `surface` property changes.
   *
   * It manages subscriptions to the components model to detect when the 'root'
   * component is created.
   *
   * @param changedProperties Map of changed properties.
   */
  protected override willUpdate(changedProperties: PropertyValues) {
    if (changedProperties.has('surface')) {
      if (this.unsubscribe) {
        this.unsubscribe();
        this.unsubscribe = undefined;
      }
      this._hasRoot = !!this.surface?.componentsModel.get('root');

      if (this.surface && !this._hasRoot) {
        const sub = this.surface.componentsModel.onCreated.subscribe(comp => {
          if (comp.id === 'root') {
            this._hasRoot = true;
            this.requestUpdate();
            this.unsubscribe?.();
            this.unsubscribe = undefined;
          }
        });
        this.unsubscribe = () => sub.unsubscribe();
      }
    }
  }

  /**
   * Cleans up subscriptions.
   */
  override disconnectedCallback() {
    super.disconnectedCallback();
    if (this.unsubscribe) {
      this.unsubscribe();
      this.unsubscribe = undefined;
    }
  }

  /**
   * Renders the surface.
   *
   * If `surface` is not set, returns `nothing`.
   * If the root component is not yet available, renders a loading state.
   * Otherwise, renders the root component using `renderA2uiNode`.
   */
  override render() {
    if (!this.surface) return nothing;
    if (!this._hasRoot) {
      return html`<slot name="loading"><div>Loading surface...</div></slot>`;
    }

    try {
      const rootContext = new ComponentContext(this.surface, 'root', '/');
      return html`${renderA2uiNode(rootContext, this.surface.defaultCatalog)}`;
    } catch (e) {
      console.error('Error creating root context:', e);
      return html`<div>Error rendering surface</div>`;
    }
  }
}
