// renderers/react/src/v0_9/catalog/basic/components/ChoicePicker.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, {useState} from 'react';
import {createComponentImplementation} from '../../../adapter';
import {ChoicePickerApi} from '@a2ui/web_core/v0_9/basic_catalog';
import {useBasicCatalogStyles} from '../utils';
import styles from './ChoicePicker.module.css';

// The type of an option is deeply nested into the ChoicePickerApi schema, and
// it seems z.infer is not inferring it correctly (?). We use `any` for now.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type _Option = any;

export const ChoicePicker = createComponentImplementation(ChoicePickerApi, ({props, context}) => {
  useBasicCatalogStyles();
  const [filter, setFilter] = useState('');
  const uniqueId = React.useId();
  const descriptionId = `${uniqueId}-description`;
  const errorId = `${uniqueId}-error`;
  const hasDescription = !!props.accessibility?.description;
  const hasError = props.validationErrors && props.validationErrors.length > 0;

  const describedBy =
    [hasDescription ? descriptionId : null, hasError ? errorId : null].filter(Boolean).join(' ') ||
    undefined;

  const hiddenStyle: React.CSSProperties = {
    position: 'absolute',
    width: '1px',
    height: '1px',
    padding: 0,
    margin: '-1px',
    overflow: 'hidden',
    clip: 'rect(0,0,0,0)',
    border: 0,
  };

  const values = Array.isArray(props.value) ? props.value : [];
  const isMutuallyExclusive = props.variant === 'mutuallyExclusive';

  const onToggle = (val: string) => {
    if (isMutuallyExclusive) {
      props.setValue([val]);
    } else {
      const newValues = values.includes(val)
        ? values.filter((v: string) => v !== val)
        : [...values, val];
      props.setValue(newValues);
    }
  };

  const options = (props.options || []).filter(
    (opt: _Option) =>
      !props.filterable ||
      filter === '' ||
      String(opt.label).toLowerCase().includes(filter.toLowerCase()),
  );

  const listClasses = `${styles.options} ${props.displayStyle === 'chips' ? styles.chips : ''}`;

  const errorStyle: React.CSSProperties = {
    fontSize: 'var(--a2ui-font-size-xs, 0.75rem)',
    color: 'var(--a2ui-color-error, red)',
    marginTop: '4px',
  };

  return (
    <div className={styles.host}>
      {props.label && (
        <strong id={`${uniqueId}-label`} className={styles.label}>
          {props.label}
        </strong>
      )}
      {props.filterable && (
        <input
          type="text"
          placeholder="Filter options..."
          value={filter}
          onChange={e => setFilter(e.target.value)}
          className={styles.filterInput}
        />
      )}
      <div
        className={listClasses}
        role={isMutuallyExclusive ? 'radiogroup' : 'group'}
        aria-labelledby={props.label ? `${uniqueId}-label` : undefined}
        aria-label={props.accessibility?.label}
        aria-invalid={hasError ? 'true' : 'false'}
        aria-describedby={describedBy}
      >
        {options.map((opt: _Option, i: number) => {
          const isSelected = values.includes(opt.value);
          if (props.displayStyle === 'chips') {
            return (
              <button
                key={i}
                onClick={() => onToggle(opt.value)}
                className={`${styles.chip} chip ${isSelected ? `${styles.selected} selected` : ''}`}
                aria-pressed={isSelected}
              >
                {opt.label}
              </button>
            );
          }
          return (
            <label key={i} className={styles.optionLabel}>
              <input
                type={isMutuallyExclusive ? 'radio' : 'checkbox'}
                checked={isSelected}
                onChange={() => onToggle(opt.value)}
                name={isMutuallyExclusive ? `choice-${context.componentModel.id}` : undefined}
              />
              <span className={styles.optionText}>{opt.label}</span>
            </label>
          );
        })}
      </div>
      {hasError && (
        <span id={errorId} style={errorStyle}>
          {props.validationErrors?.[0]}
        </span>
      )}
      {hasDescription && (
        <span id={descriptionId} style={hiddenStyle}>
          {props.accessibility?.description}
        </span>
      )}
    </div>
  );
});

// renderers/angular/src/v0_9/catalog/basic/choice-picker.component.ts
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, computed, ChangeDetectionStrategy} from '@angular/core';
import {BasicCatalogComponent} from './basic-catalog-component';
import {ChoicePickerApi} from '@a2ui/web_core/v0_9/basic_catalog';

/**
 * Angular implementation of the A2UI ChoicePicker component (v0.9).
 *
 * Renders a set of options as either radio buttons/checkboxes or chips.
 * Supports both single and multiple selection.
 *
 * Supported CSS variables:
 * - `--a2ui-choicepicker-gap`: Controls spacing between options/chips.
 * - `--a2ui-choicepicker-padding`: Controls padding of the container.
 * - `--a2ui-choicepicker-checkbox-size`: Controls size of checkboxes/radios.
 * - `--a2ui-choicepicker-chip-padding`: Controls padding of chips.
 * - `--a2ui-choicepicker-chip-border-radius`: Controls border radius of chips.
 * - `--a2ui-choicepicker-chip-border`: Controls border of chips.
 * - `--a2ui-choicepicker-chip-background`: Controls background of chips.
 * - `--a2ui-choicepicker-chip-background-selected`: Controls background of selected chips.
 */
@Component({
  selector: 'a2ui-v09-choice-picker',
  standalone: true,
  imports: [],
  template: `
    <div class="a2ui-choice-picker">
      @if (label()) {
        <strong [id]="uniqueId + '-label'" class="a2ui-choice-picker-label">{{ label() }}</strong>
      }

      <!-- Chips Variant -->
      @if (displayStyle() === 'chips') {
        <div
          class="a2ui-chips-group"
          [attr.role]="groupRole()"
          [attr.aria-labelledby]="label() ? uniqueId + '-label' : null"
          [attr.aria-label]="props()['accessibility']?.value()?.label"
          [attr.aria-invalid]="props()['isValid']?.value() === false ? 'true' : 'false'"
          [attr.aria-describedby]="describedBy()"
        >
          @for (option of options(); track option.value) {
            <button
              class="a2ui-chip"
              [class.active]="isSelected(option.value)"
              [attr.aria-pressed]="isSelected(option.value)"
              (click)="toggleActive(option.value)"
            >
              {{ option.label }}
            </button>
          }
        </div>
      } @else {
        <!-- Checkbox/Radio Variant -->
        <div
          class="a2ui-options-group"
          [attr.role]="groupRole()"
          [attr.aria-labelledby]="label() ? uniqueId + '-label' : null"
          [attr.aria-label]="props()['accessibility']?.value()?.label"
          [attr.aria-invalid]="props()['isValid']?.value() === false ? 'true' : 'false'"
          [attr.aria-describedby]="describedBy()"
        >
          @for (option of options(); track option.value) {
            <label class="a2ui-option-label">
              <input
                [type]="isMultiple() ? 'checkbox' : 'radio'"
                [name]="componentId()"
                [value]="option.value"
                [checked]="isSelected(option.value)"
                (change)="onCheckChange(option.value, $event)"
                class="a2ui-option-input"
              />
              <span class="a2ui-option-text">{{ option.label }}</span>
            </label>
          }
        </div>
      }

      @if (props()['validationErrors']?.value()?.length) {
        <div [id]="uniqueId + '-error'">
          @for (message of props()['validationErrors']?.value(); track message) {
            <div class="a2ui-error-message">{{ message }}</div>
          }
        </div>
      }

      @if (props()['accessibility']?.value()?.description) {
        <span
          [id]="uniqueId + '-description'"
          style="position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); border: 0;"
        >
          {{ props()['accessibility']?.value()?.description }}
        </span>
      }
    </div>
  `,
  styles: [
    `
      .a2ui-choice-picker {
        width: 100%;
        padding: var(--a2ui-choicepicker-padding, 0);
        display: flex;
        flex-direction: column;
        gap: var(--a2ui-spacing-xs, 4px);
      }
      .a2ui-choice-picker-label {
        font-size: var(
          --a2ui-choicepicker-label-font-size,
          var(--a2ui-label-font-size, var(--a2ui-font-size-s, 14px))
        );
        font-weight: bold;
        color: var(--a2ui-text-color-text, var(--a2ui-color-on-background, #333));
        margin-bottom: 4px;
      }
      .a2ui-options-group {
        display: flex;
        flex-direction: column;
        gap: var(--a2ui-choicepicker-gap, var(--a2ui-spacing-xs, 0.25rem));
      }
      .a2ui-option-label {
        display: flex;
        align-items: center;
        gap: var(--a2ui-choicepicker-gap, var(--a2ui-spacing-xs, 0.25rem));
        cursor: pointer;
        color: var(--a2ui-text-color-text, var(--a2ui-color-on-background, #333));
      }
      .a2ui-option-input {
        width: var(--a2ui-choicepicker-checkbox-size, 1rem);
        height: var(--a2ui-choicepicker-checkbox-size, 1rem);
      }
      .a2ui-chips-group {
        display: flex;
        flex-wrap: wrap;
        gap: var(--a2ui-choicepicker-gap, var(--a2ui-spacing-xs, 0.25rem));
      }
      .a2ui-chip {
        padding: var(
          --a2ui-choicepicker-chip-padding,
          var(--a2ui-spacing-s, 0.5rem) var(--a2ui-spacing-m, 1rem)
        );
        border-radius: var(--a2ui-choicepicker-chip-border-radius, 100px);
        border: var(--a2ui-choicepicker-chip-border, 1px solid var(--a2ui-color-border, #ccc));
        background: var(--a2ui-choicepicker-chip-background, var(--a2ui-color-surface, #fff));
        cursor: pointer;
        transition: all 0.2s;
      }
      .a2ui-chip.active {
        background-color: var(
          --a2ui-choicepicker-chip-background-selected,
          var(--a2ui-color-primary, #17e)
        );
        color: var(--a2ui-color-on-primary, #fff);
        border-color: var(
          --a2ui-choicepicker-chip-background-selected,
          var(--a2ui-color-primary, #17e)
        );
      }
      .a2ui-error-message {
        color: var(--a2ui-color-error, red);
        font-size: var(--a2ui-font-size-xs, 12px);
        margin-top: 4px;
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ChoicePickerComponent extends BasicCatalogComponent<typeof ChoicePickerApi> {
  readonly groupRole = computed(() =>
    this.variant() === 'multipleSelection' ? 'group' : 'radiogroup',
  );
  readonly label = computed(() => this.props()['label']?.value());
  readonly displayStyle = computed(() => this.props()['displayStyle']?.value());
  readonly options = computed(() => this.props()['options']?.value() || []);
  readonly variant = computed(() => this.props()['variant']?.value());
  readonly selectedValue = computed(() => this.props()['value']?.value());

  readonly describedBy = computed(() => {
    const hasError = this.props()['isValid']?.value() === false;
    const hasDesc = !!this.props()['accessibility']?.value()?.description;
    const ids: string[] = [];
    if (hasDesc) {
      ids.push(`${this.uniqueId}-description`);
    }
    if (hasError) {
      ids.push(`${this.uniqueId}-error`);
    }
    return ids.length > 0 ? ids.join(' ') : null;
  });

  isMultiple(): boolean {
    return this.variant() === 'multipleSelection';
  }

  isSelected(value: string): boolean {
    const selected = this.selectedValue();
    if (Array.isArray(selected)) {
      return selected.includes(value);
    }
    return selected === value;
  }

  onCheckChange(value: string, event: Event) {
    const checked = (event.target as HTMLInputElement).checked;
    this.updateValue(value, checked);
  }

  toggleActive(value: string) {
    const current = this.isSelected(value);
    this.updateValue(value, !current);
  }

  private updateValue(value: string, active: boolean) {
    const current = this.selectedValue();
    if (this.isMultiple()) {
      let next = Array.isArray(current) ? [...current] : [];
      if (active) {
        if (!next.includes(value)) next.push(value);
      } else {
        next = next.filter((v: any) => v !== value);
      }
      this.props()['value']?.onUpdate(next);
    } else {
      if (active) {
        this.props()['value']?.onUpdate([value]);
      }
    }
  }
}
