// renderers/react/src/v0_9/catalog/basic/components/Button.tsx
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {createComponentImplementation} from '../../../../adapter';
import {ButtonApi} from '@a2ui/web_core/v0_9/basic_catalog';
import {useBasicCatalogStyles} from '../utils';
import styles from './Button.module.css';

export const Button = createComponentImplementation(ButtonApi, ({props, buildChild}) => {
  useBasicCatalogStyles();

  const classes = [styles.button];
  if (props.variant === 'primary') {
    classes.push(styles.primary);
  } else if (props.variant === 'borderless') {
    classes.push(styles.borderless);
  }

  return (
    <button className={classes.join(' ')} onClick={props.action} disabled={props.isValid === false}>
      {props.child ? buildChild(props.child) : null}
    </button>
  );
});

// renderers/lit/src/0.8/ui/button.ts
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {html, css, nothing} from 'lit';
import {customElement, property} from 'lit/decorators.js';
import {Root} from './root.js';
import {StateEvent} from '../events/events.js';
import {classMap} from 'lit/directives/class-map.js';
import * as Types from '@a2ui/web_core/types/types';
import {styleMap} from 'lit/directives/style-map.js';
import {structuralStyles} from './styles.js';

@customElement('a2ui-button')
export class Button extends Root {
  @property()
  accessor action: Types.Action | null = null;

  @property()
  accessor primary: boolean | null = false;

  static override styles = [
    structuralStyles,
    css`
      :host {
        display: block;
        flex: var(--weight);
        min-height: 0;
      }
    `,
  ];

  override render() {
    return html`<button
      class=${classMap(this.theme.components.Button)}
      style=${this.theme.additionalStyles?.Button
        ? styleMap(this.theme.additionalStyles?.Button)
        : nothing}
      @click=${() => {
        if (!this.action) {
          return;
        }
        const evt = new StateEvent<'a2ui.action'>({
          eventType: 'a2ui.action',
          action: this.action,
          dataContextPath: this.dataContextPath,
          sourceComponentId: this.id,
          sourceComponent: this.component,
        });
        this.dispatchEvent(evt);
      }}
    >
      <slot></slot>
    </button>`;
  }
}
