// renderers/react/visual-parity/react/src/main.tsx
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from 'react';
import ReactDOM from 'react-dom/client';
import {A2UIProvider, initializeDefaultCatalog} from '@a2ui/react/v0_8';
import {injectStyles} from '@a2ui/react/styles';
import {FixturePage} from './FixturePage';
import {getTheme, themeNames} from '../../fixtures/themes';

// Initialize the default component catalog
initializeDefaultCatalog();

// Inject A2UI structural CSS (required for litTheme utility classes)
injectStyles();

// Parse theme from URL parameter
const params = new URLSearchParams(window.location.search);
const themeName = params.get('theme');
const selectedTheme = getTheme(themeName);

// Add theme info to document for debugging
if (themeName) {
  document.documentElement.setAttribute('data-theme', themeName);
}

// Log available themes for debugging
console.log('[Visual Parity - React] Available themes:', themeNames);
console.log('[Visual Parity - React] Selected theme:', themeName || 'default');

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <A2UIProvider theme={selectedTheme}>
      <FixturePage />
    </A2UIProvider>
  </React.StrictMode>,
);

// renderers/lit/src/index.ts
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export type {LitComponentApi} from './types.js';
export {A2uiSurface} from './surface/a2ui-surface.js';
export {renderA2uiNode} from './surface/render-a2ui-node.js';
export {A2uiLitElement} from './a2ui-lit-element.js';
export {A2uiController} from './a2ui-controller.js';
export {Context} from './context/context.js';

/**
 * @deprecated Import v0.8 from '@a2ui/lit/v0_8'.
 * Maintained for backwards compatibility.
 *
 * This re-exports `./0.8/core.js` rather than `./0.8/index.js` on purpose.
 * `0.8/index.js` also pulls in `0.8/ui/*`, whose `@customElement` decorators
 * register `a2ui-surface`, `a2ui-slider`, `a2ui-card`, and other tags at import
 * time. This entry point registers the version-agnostic `A2uiSurface` under the
 * same `a2ui-surface` tag, and the universal elements in `@a2ui/web_core` use
 * the other tag names, so importing `0.8/index.js` here would throw duplicate
 * `customElements.define` errors. The v0.8 elements remain available from
 * `@a2ui/lit/v0_8`.
 */
export * as v0_8 from './0.8/core.js';
