// renderers/lit/src/0.8/ui/modal.ts
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {html, css, nothing} from 'lit';
import {customElement, query, state} from 'lit/decorators.js';
import {Root} from './root.js';
import {classMap} from 'lit/directives/class-map.js';
import {styleMap} from 'lit/directives/style-map.js';
import {structuralStyles} from './styles.js';
import {ref} from 'lit/directives/ref.js';

@customElement('a2ui-modal')
export class Modal extends Root {
  static override styles = [
    structuralStyles,
    css`
      * {
        box-sizing: border-box;
      }

      dialog {
        padding: 0 0 0 0;
        border: none;
        background: none;

        & section {
          & #controls {
            display: flex;
            justify-content: end;
            margin-bottom: 4px;

            & button {
              padding: 0;
              background: none;
              width: 20px;
              height: 20px;
              pointer: cursor;
              border: none;
              cursor: pointer;
            }
          }
        }
      }
    `,
  ];

  @state()
  accessor #showModal = false;

  @query('dialog')
  accessor #modalRef: HTMLDialogElement | null = null;

  #closeModal() {
    if (!this.#modalRef) {
      return;
    }

    if (this.#modalRef.open) {
      this.#modalRef.close();
    }

    this.#showModal = false;
  }

  override render() {
    if (!this.#showModal) {
      return html`<section
        @click=${() => {
          this.#showModal = true;
        }}
      >
        <slot name="entry"></slot>
      </section>`;
    }

    return html`<dialog
      class=${classMap(this.theme.components.Modal.backdrop)}
      @click=${(evt: Event) => {
        // Only clicks on the background close the dialog.
        const [top] = evt.composedPath();
        if (!(top instanceof HTMLDialogElement)) {
          return;
        }

        this.#closeModal();
      }}
      ${ref((el?: Element) => {
        const showModalIfNeeded = () => {
          const validElement = el && el instanceof HTMLDialogElement;
          if (!validElement || el.open) {
            return;
          }

          el.showModal();
        };
        requestAnimationFrame(showModalIfNeeded);
      })}
    >
      <section
        class=${classMap(this.theme.components.Modal.element)}
        style=${this.theme.additionalStyles?.Modal
          ? styleMap(this.theme.additionalStyles?.Modal)
          : nothing}
      >
        <div id="controls">
          <button
            @click=${() => {
              this.#closeModal();
            }}
          >
            <span class="g-icon">close</span>
          </button>
        </div>
        <slot></slot>
      </section>
    </dialog>`;
  }
}

// renderers/angular/src/v0_8/components/modal.ts
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ChangeDetectionStrategy, Component, input, signal } from '@angular/core';
import { DynamicComponent } from '../rendering/dynamic-component';
import { Renderer } from '../rendering/renderer';
import type { AnyComponentNode, ModalNode } from '../types';

@Component({
  selector: 'a2ui-modal',
  imports: [Renderer],
  template: `
    <div class="a2ui-modal-entry-point" (click)="openModal()">
      @if (entryPointChild()) {
        <ng-container a2ui-renderer [surfaceId]="surfaceId()!" [component]="entryPointChild()!" />
      }
    </div>

    @if (isOpen()) {
      <div
        class="a2ui-modal-overlay"
        [class]="theme.components.Modal.backdrop"
        (click)="closeModal()"
      >
        <div
          class="a2ui-modal-content"
          [class]="theme.components.Modal.element"
          (click)="$event.stopPropagation()"
        >
          <button class="a2ui-modal-close" (click)="closeModal()">&times;</button>
          @if (contentChild()) {
            <ng-container a2ui-renderer [surfaceId]="surfaceId()!" [component]="contentChild()!" />
          }
        </div>
      </div>
    }
  `,
  styles: `
    :host {
      display: inline-block;
    }
    .a2ui-modal-entry-point {
      cursor: pointer;
    }
    .a2ui-modal-overlay {
      position: fixed;
      top: 0;
      left: 0;
      width: 100vw;
      height: 100vh;
      background: var(--a2ui-modal-backdrop-bg, rgba(0, 0, 0, 0.5));
      display: flex;
      justify-content: center;
      align-items: center;
      z-index: 1000;
    }
    .a2ui-modal-content {
      background: var(--a2ui-modal-background, var(--a2ui-color-surface, white));
      padding: var(--a2ui-modal-padding, var(--a2ui-spacing-xl, 32px));
      border-radius: var(--a2ui-modal-border-radius, var(--a2ui-border-radius, 8px));
      position: relative;
      min-width: 300px;
      max-width: 80%;
      max-height: 80%;
      overflow-y: auto;
      box-shadow: var(--a2ui-modal-box-shadow, 0 10px 25px rgba(0, 0, 0, 0.2));
    }
    .a2ui-modal-close {
      position: absolute;
      top: 10px;
      right: 15px;
      border: none;
      background: none;
      font-size: 24px;
      cursor: pointer;
      color: var(--a2ui-text-caption-color, #999);
    }
    .a2ui-modal-close:hover {
      color: var(--a2ui-text-color, #333);
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Modal extends DynamicComponent<ModalNode> {
  readonly entryPointChild = input.required<AnyComponentNode>();
  readonly contentChild = input.required<AnyComponentNode>();

  protected readonly isOpen = signal(false);

  openModal() {
    this.isOpen.set(true);
  }

  closeModal() {
    this.isOpen.set(false);
  }
}
