// renderers/lit/src/0.8/ui/row.ts
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {html, css, nothing} from 'lit';
import {customElement, property} from 'lit/decorators.js';
import {Root} from './root.js';
import {classMap} from 'lit/directives/class-map.js';
import * as Types from '@a2ui/web_core/types/types';
import {styleMap} from 'lit/directives/style-map.js';
import {structuralStyles} from './styles.js';

@customElement('a2ui-row')
export class Row extends Root {
  @property({reflect: true, type: String})
  accessor alignment: Types.ResolvedRow['alignment'] = 'stretch';

  @property({reflect: true, type: String})
  accessor distribution: Types.ResolvedRow['distribution'] = 'start';

  static override styles = [
    structuralStyles,
    css`
      * {
        box-sizing: border-box;
      }

      :host {
        display: flex;
        flex: var(--weight);
      }

      section {
        display: flex;
        flex-direction: row;
        width: 100%;
        min-height: 100%;
      }

      :host([alignment='start']) section {
        align-items: start;
      }

      :host([alignment='center']) section {
        align-items: center;
      }

      :host([alignment='end']) section {
        align-items: end;
      }

      :host([alignment='stretch']) section {
        align-items: stretch;
      }

      :host([distribution='start']) section {
        justify-content: start;
      }

      :host([distribution='center']) section {
        justify-content: center;
      }

      :host([distribution='end']) section {
        justify-content: end;
      }

      :host([distribution='spaceBetween']) section {
        justify-content: space-between;
      }

      :host([distribution='spaceAround']) section {
        justify-content: space-around;
      }

      :host([distribution='spaceEvenly']) section {
        justify-content: space-evenly;
      }
    `,
  ];

  override render() {
    return html`<section
      class=${classMap(this.theme.components.Row)}
      style=${this.theme.additionalStyles?.Row
        ? styleMap(this.theme.additionalStyles?.Row)
        : nothing}
    >
      <slot></slot>
    </section>`;
  }
}

// renderers/angular/src/v0_8/components/row.ts
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { DynamicComponent } from '../rendering/dynamic-component';
import { Renderer } from '../rendering/renderer';
import type { AnyComponentNode, ResolvedRow, RowNode } from '../types';

@Component({
  selector: 'a2ui-row',
  imports: [Renderer],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[attr.alignment]': 'alignment()',
    '[attr.distribution]': 'distribution()',
  },
  styles: `
    :host {
      display: flex;
      flex: var(--weight);
    }

    section {
      display: flex;
      flex-direction: row;
      width: 100%;
      min-height: 100%;
      box-sizing: border-box;
    }

    .align-start {
      align-items: start;
    }

    .align-center {
      align-items: center;
    }

    .align-end {
      align-items: end;
    }

    .align-stretch {
      align-items: stretch;
    }

    .distribute-start {
      justify-content: start;
    }

    .distribute-center {
      justify-content: center;
    }

    .distribute-end {
      justify-content: end;
    }

    .distribute-spaceBetween {
      justify-content: space-between;
    }

    .distribute-spaceAround {
      justify-content: space-around;
    }

    .distribute-spaceEvenly {
      justify-content: space-evenly;
    }
  `,
  template: `
    <section [class]="classes()" [style]="theme.additionalStyles?.Row">
      @for (child of children() ?? component().properties.children; track child?.id ?? child) {
        @if (child) {
          <ng-container a2ui-renderer [surfaceId]="surfaceId()!" [component]="child" />
        }
      }
    </section>
  `,
})
export class Row extends DynamicComponent<RowNode> {
  readonly alignment = input<ResolvedRow['alignment']>('stretch');
  readonly distribution = input<ResolvedRow['distribution']>('start');
  readonly children = input<AnyComponentNode[] | null>();

  protected readonly classes = computed(() => ({
    ...this.theme.components.Row,
    [`align-${this.alignment()}`]: true,
    [`distribute-${this.distribution()}`]: true,
  }));
}
